### PR TITLE
avoid missing attribute crash

### PR DESCRIPTION
**Pull request by mattchg**
Added a column to partner table and tested using `o r codegen`.

This code path doesn't seem necessary, but I'm not completely sure

### CODE REVIEW

**Review by dsgkirkby — APPROVED** [review]
Sure 👍 any idea why this isn't present?

**Comment by mattchg** [comment]
Usually column.server_default is a `DefaultClause` but for the id column of the plan table  column.server_default is an `Identity` class since it's an autoincremented column, and that class doesn't have an `arg` attribute.

Maybe it's a bug that is fixed upstream?

**Comment by dsgkirkby** [comment]
I took a quick peek and it that code looked different, might be worth trying to pull upstream yeah. If it's painful to do so then this is fine

**Comment by mattchg** [comment]
I'm going to merge this since it's blocking some work I'm doing and attempting to pull from upstream was a bit more complicated than I thought (I've also never done it before). I'll file a ticket to follow up

**Comment by dsgkirkby** [comment]
Sounds good 👍 we can note in the ticket that this commit can likely be reverted as part of pulling from upstream

**Pull request merged**
